//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiSua.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopSuaEntities : DbContext
    {
        public ShopSuaEntities()
            : base("name=ShopSuaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DatHang> DatHang { get; set; }
        public virtual DbSet<DatHang_ChiTiet> DatHang_ChiTiet { get; set; }
        public virtual DbSet<HangSX> HangSX { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<LoaiSua> LoaiSua { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<Sua> Sua { get; set; }
        public virtual DbSet<ThuKho> ThuKho { get; set; }
    }
}
