//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiSua.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Sua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sua()
        {
            this.DatHang_ChiTiet = new HashSet<DatHang_ChiTiet>();
        }

        [Display(Name = "Mã sữa")]
        public int ID { get; set; }

        [Display(Name = "Hãng sản xuất")]
        [Required(ErrorMessage = "Chưa chọn hãng sản xuất!")]
        public Nullable<int> HangSX_ID { get; set; }

        [Display(Name = "Loại sữa")]
        [Required(ErrorMessage = "Chưa chọn Loại sữa!")]
        public Nullable<int> LoaiSua_ID { get; set; }

        [Display(Name = "Tên sữa")]
        [Required(ErrorMessage = "Tên sữa không được bỏ trống!")]
        public string TenSua { get; set; }

        [Display(Name = "Giá sữa")]
        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = false)]
        [Required(ErrorMessage = "Đơn giá không được bỏ trống!")]
        public Nullable<int> DonGia { get; set; }

        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Số lượng không được bỏ trống")]
        public Nullable<int> SoLuong { get; set; }

        [Display(Name = "Ảnh mẫu sản phẩm")]
        [Required(ErrorMessage = "Hình ảnh sản phẩm")]
        public string AnhMau { get; set; }

        public HttpPostedFileBase HinhAnhBia { get; set; }
        
        [Display(Name = "Mô tả sản phẩm")]
        [DataType(DataType.MultilineText)]
        public string MoTa { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHang_ChiTiet> DatHang_ChiTiet { get; set; }
        public virtual HangSX HangSX { get; set; }
        public virtual LoaiSua LoaiSua { get; set; }
    }
}
